version: "3.5"

services:
  offchain-ipfs-node:
    image: ipfs/go-ipfs
    container_name: offchain-ipfs-node
    ports:
      - 8080:8080
    volumes:
      - ../ipfs/offchain:/data/ipfs

  offchain-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: offchain-web
    container_name: offchain-web
    environment:
      IPFS_URL: 'http://offchain-ipfs-node:5001/api/v0'
    ports:
      - 5000:5000
    depends_on:
      - offchain-ipfs-node
