version: "3.5"

services:
  image-uploader-ipfs-node:
    image: ipfs/go-ipfs
    container_name: image-uploader-ipfs-node
    ports:
      - 8080:8080
    volumes:
      - ../ipfs/image-uploader:/data/ipfs

  image-uploader-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: image-uploader-web
    container_name: image-uploader-web
    environment:
      IPFS_URL: 'http://image-uploader-ipfs-node:5001/api/v0'
    ports:
      - 5000:5000
    depends_on:
      - image-uploader-ipfs-node
